#!/usr/bin/python
# -*- coding: utf-8 -*-
import sys
import uuid
import requests
import hashlib
import time
import json
from importlib import reload

reload(sys)

YOUDAO_URL = "https://openapi.youdao.com/api"
# TODO APP KEY
APP_KEY = ""
# TODO APP SECRET
APP_SECRET = ""


def encrypt(signStr):
    hash_algorithm = hashlib.sha256()
    hash_algorithm.update(signStr.encode("utf-8"))
    return hash_algorithm.hexdigest()


def truncate(q):
    if q is None:
        return None
    size = len(q)
    return q if size <= 20 else q[0:10] + str(size) + q[size - 10 : size]


def do_request(data):
    headers = {"Content-Type": "application/x-www-form-urlencoded"}
    return requests.post(YOUDAO_URL, data=data, headers=headers)


def connect():
    if len(sys.argv) < 2:
        print("Invalid input")
        return
    q = sys.argv[1]

    data = {}
    data["from"] = "auto"
    data["to"] = "zh-CHS"
    data["signType"] = "v3"
    curtime = str(int(time.time()))
    data["curtime"] = curtime
    salt = str(uuid.uuid1())
    signStr = APP_KEY + truncate(q) + salt + curtime + APP_SECRET
    sign = encrypt(signStr)
    data["appKey"] = APP_KEY
    data["q"] = q
    data["salt"] = salt
    data["sign"] = sign
    data["vocabId"] = "您的用户词表ID"

    response = do_request(data)
    contentType = response.headers["Content-Type"]
    if contentType == "audio/mp3":
        millis = int(round(time.time() * 1000))
        filePath = "合成的音频存储路径" + str(millis) + ".mp3"
        fo = open(filePath, "wb")
        fo.write(response.content)
        fo.close()
    else:
        data = str(response.content, "utf-8")
        j = json.loads(data)
        basic = j.get("basic", {})
        j = {
            "explains": basic.get("explains", []),
            "us-phonetic": basic.get("us-phonetic", ""),
            "web": j.get("web", {}),
        }
        data = json.dumps(j, ensure_ascii=False)
        print(data)


if __name__ == "__main__":
    connect()
